### ISSUE TITLE
请问您是移除了对ARM移动设备的支持了吗？

### ISSUE THREAD

**Issue by Moreki** [jskyzero/MoePicture#1]
rt

**Comment by jskyzero** [comment]
唔，最近几个版本似乎打包的时候没有勾选ARM平台，原因如下：
1. 目前运行 Win10 ARM PC设备所占比重似乎很少，我对此了解甚少。
2. Win10 mobile 似乎很久未更新（换句话说，未能有像桌面版一样的更新频率），现在的UI已经使用了Win10 新版本的亚克力材质等流畅设计语言的接口，无法确保能无差错在旧版本系统上运行（同样的理由，每次更新商店中我也只会保留对应当前最新系统版本的安装包）。
3. 因为商店中似乎会将所有平台的包的集成大小显示为应用大小，我不太想给别人第一眼这个软件很大的错觉。

从打包的角度来讲，似乎只是多一个勾选的事情，但是我还是希望既然要做就要确保对应平台能确定能运行，提供相似的体验，这可能需要一定的付出，而我自己已经早就放弃使用运行 Win10 mobile 的手机，也没有运行 Win10 ARM 的其他设备，主观上我认为目标用户可能较少，花时间去适配不一定值得。

但是既然您问了这个问题，可能您是有对应的需求的，只要您确实的有这个需要，我可以在下个版本的更新计划中重新加入对ARM移动设备的支持，为此我可能需要您提供以下您的设备的基本信息（比如型号，系统版本，屏幕大小），方便进行适配调试。

最后非常感谢您的反馈，如果对应用本身有任何建议或者意见都可以反馈给我，这个应用本身就是因为兴趣爱好做的，有愿意使用的人，或者一定程度上帮到使用的用户我就很满足了，如果您喜欢，可以在商店给出好评，给项目点个star，或者将应用分享给需要的其他人，十分感谢。

**Comment by Moreki** [comment]
你好，Win 10m去年被宣告停止版本迭代而仅进行安全性更新后，基本就是弃子状态。不过好在还有许多优秀的应用支撑其备胎的资格。
我的型号是Lumia-1520 
版本 1703 
OS 15063
屏幕 6英寸
期待开放捐助入口~

**Comment by jskyzero** [comment]
十分抱歉，个人能力精力有限，最新版本的安装包已经勾选了ARM平台，但是没有做适配，目前系统大量使用Win10新版本的接口，我不清楚现在Win10移动端这些接口的实现情况，如果只是UI的适配倒还好。

十分抱歉，您可以试着下载最新版本的安装包，试着安装，如果出现什么问题可以再跟我反馈。
